function prompt_my() {
  # p10k segment -t '%B%1F[%3F%n%2F@%4F%m %5F%1~%1F]%7F%(#.#.$)%f%b'
  p10k segment -t '%B%1F[%3F%n%2F@ %5F%1~%1F]%7F%(#.#.$)%f%b'
}

unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(my)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_DISABLE_HOT_RELOAD=true
POWERLEVEL9K_LEFT_RIGHT_WHITESPACE=
POWERLEVEL9K_LEFT_LEFT_WHITESPACE=
POWERLEVEL9K_BACKGROUND=
POWERLEVEL9K_MODE=ascii

typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
# typeset -g POWERLEVEL9K_INSTANT_PROMPT=off

(( ! $+functions[p10k] )) || p10k reload
